spring.application.name=test

#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=devuser
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# mybatis
mybatis.config=classpath:db/mybatis/config/mybatis-config.xml
mybatis.mapper-locations=classpath:db/mybatis/mapper/*.xml
mybatis.type-aliases-package=com.admin.dbwork.dto
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.lazy-loading-enabled=false

# MyBatis 쿼리 로그 출력
#logging.level.com.admin.dbwork.mapper=DEBUG